// Copy to config.js for local testing. In production, config.js is generated by CI.
window.AQ_CONFIG = {
  apiBaseUrl: "https://r2fihr72e5.execute-api.ap-southeast-2.amazonaws.com/prod",
  deferredInviteSecret: "YOUR_CHALLENGE_DEFERRED_INVITE_SECRET",
};
